Program: Mierzalny.cpp Stoper.cpp TablicaO1.cpp TablicaX2.cpp mergesort.cpp main.cpp
	g++ -c -MMD -MP -MF Mierzalny.d -MT Mierzalny.o -o Mierzalny.o Mierzalny.cpp
	g++ -c -MMD -MP -MF Stoper.d -MT Stoper.o -o Stoper.o Stoper.cpp
	g++ -c -MMD -MP -MF TablicaO1.d -MT Stoper.o -o TablicaO1.o TablicaO1.cpp
	g++ -c -MMD -MP -MF TablicaX2.d -MT TablicaX2.o -o TablicaX2.o TablicaX2.cpp
	g++ -c -MMD -MP -MF mergesort.d -MT mergesort.o -o mergesort.o mergesort.cpp
	g++ -c -MMD -MP -MF main.d -MT main.o -o main.o main.cpp
	g++ -o Program  Mierzalny.o Stoper.o TablicaO1.o TablicaX2.o mergesort.o main.o
